import "./globals.css";
import localFont from "next/font/local";

const geistSans = localFont({
  src: [
    {
      path: "/fonts/Geist/webfonts/GeistSans-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/Geist/webfonts/GeistSans-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-geist-sans",
});

const geistMono = localFont({
  src: [
    {
      path: "/fonts/GeistMono/webfonts/GeistMono-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "/fonts/GeistMono/webfonts/GeistMono-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-geist-mono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
